package devflow.agent.executor;

public enum GenerationFailureType {
    MODEL_INVOCATION_FAILED,
    ATTEMPT_TIMEOUT,
    OUTPUT_TRUNCATED,
    INVALID_PATCH_JSON,
    PATCH_SCHEMA_INVALID,
    EDIT_UNIT_SCOPE_VIOLATION,
    SYMBOL_NOT_FOUND,
    TREE_SITTER_PARSE_FAILED,
    RESULT_FILE_INVALID
}
