package devflow.agent.executor;

/**
 * 工具级失败码。
 *
 * <p>这层只表达本地工具/本地验证的结果，不表达流程语义。
 */
public enum ToolFailureCode {
    PATCH_APPLY_FAILED,
    PATCH_SCHEMA_INVALID,
    PATCH_SCOPE_VIOLATION,
    PATCH_SYMBOL_NOT_FOUND,
    PATCH_ANCHOR_MISSING,
    EXACT_EDIT_BASE_STATE_MISMATCH,
    EXACT_EDIT_TARGET_NOT_FOUND,
    EXACT_EDIT_TARGET_NOT_UNIQUE,
    TREE_SITTER_PARSE_FAILED,
    GENERATED_CONTENT_EMPTY,
    HTML_STRUCTURE_INVALID,
    RUNTIME_WIRING_INVALID,
    JAVASCRIPT_STRUCTURE_INVALID,
    INLINE_SCRIPT_INVALID,
    CONTENT_VALIDATION_EXCEPTION,
    GENERATED_CONTENT_INVALID,
    COMMAND_FAILED,
    RESOURCE_MISSING,
    JAVASCRIPT_SYNTAX_INVALID,
    PLAYWRIGHT_PROBE_PAYLOAD_INVALID,
    PLAYWRIGHT_PROBE_EXECUTION_FAILED,
    TEST_CASES_MISSING,
    TEST_EXECUTOR_UNAVAILABLE,
    TEST_CASE_EXECUTION_FAILED,
    RUNTIME_SNAPSHOT_CAPTURE_FAILED
}
