package devflow.agent.executor;

/**
 * 工具级失败码。
 *
 * <p>这层只表达本地工具/本地验证的结果，不表达流程语义。
 */
public enum ToolFailureCode {
    APPLY_FAILED,
    MODEL_OUTPUT_INVALID,
    TARGET_SCOPE_VIOLATION,
    TARGET_NOT_ADDRESSABLE,
    SNAPSHOT_STALE,
    TARGET_NOT_FOUND,
    TARGET_NOT_UNIQUE,
    SYNTAX_INVALID,
    NO_MATERIAL_CHANGE,
    GENERATED_CONTENT_EMPTY,
    HTML_STRUCTURE_INVALID,
    RUNTIME_WIRING_INVALID,
    JAVASCRIPT_STRUCTURE_INVALID,
    INLINE_SCRIPT_INVALID,
    CONTENT_VALIDATION_EXCEPTION,
    GENERATED_CONTENT_INVALID,
    COMMAND_FAILED,
    RESOURCE_MISSING,
    JAVASCRIPT_SYNTAX_INVALID,
    PLAYWRIGHT_PROBE_PAYLOAD_INVALID,
    PLAYWRIGHT_PROBE_EXECUTION_FAILED,
    TEST_CASES_MISSING,
    TEST_EXECUTOR_UNAVAILABLE,
    TEST_CASE_EXECUTION_FAILED,
    RUNTIME_SNAPSHOT_CAPTURE_FAILED
}
